on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
          HATENA_TOKEN: ${{ secrets.HATENA_TOKEN }}
          KV_ORIGIN: ${{ secrets.KV_ORIGIN }}
          PYTHONUNBUFFERED: "1"
